### ISSUE TITLE
mouse pointer is not set

### ISSUE THREAD

**Issue by 2-www** [dimtpap/coppwr#11]
**System information**
- **coppwr** version (See in Help → About): 1.5.1
- **coppwr** installation method (Flathub, AUR, .deb, .rpm): Flathub
- **PipeWire** version (See with `pipewire --version`): 1.0.3
- OS: debian
- Desktop environment/Window manager: GNOME

**Describe the bug**
the pointer is either invisible or what it last was in the previous window, like I or sometimes the resizing pointer, sometimes the normal pointer

**To Reproduce**
open coppwr

**Expected behavior**
the pointer is the usual pointer that points

**Comment by dimtpap** [comment]
Is this still a problem in 1.6.0?
