### ISSUE TITLE
Explanations on the different graphs in the profiler tab

### ISSUE THREAD

**Issue by motsgar** [dimtpap/coppwr#14]
Would it be possible to get some explanations on the different graphs in the profiler tab? The data seems cool especially since I'm developing audio playback software and trying to minimize latency, but wordings like "Client End Date" when then the values are microseconds doesn't really mean anything to me or explain what it actually is.
Seeing more detailed explanations either in some documentation or e.g. tooltips when hovering on the texts would be cool.

**Comment by dimtpap** [comment]
FYI
- Driver delay: Delay to device
- Driver period: Time between when the previous cycle started and when the current cycle started
- Driver "Estimated": Estimated time until the next cycle starts
- Driver End Date: Time between when the current cycle started and when the driver finished processing/current cycle ended
- Client End Date: Time between when the current cycle started and when the client finished processing
- Client Scheduling Latency: Time between when the client was ready to start processing and when it actually started processing
- Client Duration: Time between when the client started processing and when it finished and woke up the next nodes in the graph

See also `man pw-top`
