### ISSUE TITLE
Ability to zoom/resize the graph?

### ISSUE THREAD

**Issue by mxmilkiib** [dimtpap/coppwr#2]
It's a bit congested on 1080!

![image](https://github.com/dimtpap/coppwr/assets/108225/298208ea-efab-455c-95ee-2f44bfb64595)

Thanks!

**Comment by dimtpap** [comment]
Related: https://github.com/setzer22/egui_node_graph/pull/101

**Comment by dewiweb** [comment]
Is there any news about zoom/resize implementation?

**Comment by dimtpap** [comment]
> Is there any news about zoom/resize implementation?

It doesn't look like the upstream project has any activity so I'll try to merge the mentioned PR into https://github.com/dimtpap/egui_node_graph soon. But that's already a fork of a fork so it may take a little bit

**Comment by mxmilkiib** [comment]
@setzer22 excuse me for the ping, but there is a major choke point in the library. I'm wondering if you might be getting back to it at some point or if you've more moved onto further projects. Asking so we can all get a clearer picture of what the future might hold so that energies aren't misdirected due to the ambiguity, especially given the forks. Thank you!
