### ISSUE TITLE
Incorrect UI scaling

### ISSUE THREAD

**Issue by dromer** [dimtpap/coppwr#6]
At the moment the default size is rather huge, which makes the entire UI very difficult to view and navigate.
For the graph we can zoom out, but the rest of the UI is still very bulky this way.

Please add an option to change the default font size, so we can adjust the way the entire UI gets sized.

**Comment by dimtpap** [comment]
This may be a bug, can you provide a screenshot?

**Comment by dromer** [comment]
Sure:

![](https://i.imgur.com/033aj9Z.png)

**Comment by dimtpap** [comment]
I tried on latest Ubuntu X11 and got the same behavior. Linux Mint X11 though had no problems. What distro and window system are you running?

**Comment by dromer** [comment]
Debian 12 and X11

**Comment by dimtpap** [comment]
The scaling is set based on [`Xft.dpi`](https://wiki.archlinux.org/title/HiDPI#X_Resources), maybe it's not set correctly in your setup. As a workaround you can run coppwr with the `WINIT_X11_SCALE_FACTOR` environment variable. For example `WINIT_X11_SCALE_FACTOR=1 coppwr`

**Comment by dromer** [comment]
Indeed `WINIT_X11_SCALE_FACTOR` is not set. If I set it to 1 everything looks good!

So maybe default to 1 when the env-var is not used?

**Comment by dimtpap** [comment]
It may be a bug with winit, the windowing library used by coppwr, that should be reported. I'll try messing with `Xft.dpi` to see if it's respected. If it is, it's an end-user X11 configuration issue, otherwise it's a bug in winit

**Comment by dromer** [comment]
Hmm, I don't think expecting unused envvars to be set makes a lot of sense.
This is actually the first time I hear about this one.

Can you check with the winit devs then? This is a bit out of my league (I'm just a poor user).

**Comment by dimtpap** [comment]
> Maybe related? -> [rust-windowing/winit#2231](https://github.com/rust-windowing/winit/issues/2231)

Yes, winit falls back to a manual calculation of the factor based on the display's properties if neither `Xft.dpi` nor the env var are set. Thanks for linking it
